export const homePageRoute = () => "/"
export const loginPageRoute = () => "/login"
export const registerPageRoute = () => "/register"
export const expensesPageRoute = () => "/expenses"
export const createExpensePageRoute = () => "/expenses/create"
